// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChats():Promise<Array<main.Chat>>;

export function GetMessages(arg1:number):Promise<Array<main.Message>>;

export function SearchChats(arg1:string):Promise<Array<main.Chat>>;

export function SendMessage(arg1:number,arg2:string):Promise<main.Message>;
